---
- hosts: all
  become: yes
  tasks:
    - name: UnLoad docker image
      docker_image:
        name: presto
        tag: local
        force_absent: true
        state: absent

    - name: Load docker image
      docker_image:
        source: load
        name: presto
        force_source: true
        force_tag: true
        load_path: /vagrant/tmp/dockerImage.tar
        state: present
        timeout: 120

    - name: Terraform
      terraform:
        project_path: ../terraform
        force_init: true
        state: present
      register: terraform

    - name: Terraform stdout
      debug:
        msg: "{{terraform.stdout}}"

    - name: Test healthchecks of services
      include_tasks: test.yml
      # variable mode setup via extra_args in Vagrant.ansible_local or bash -> ANSIBLE_ARGS='--extra-vars "mode=test"' vagrant up --provision
      when: mode == "test"